#!/usr/bin/env sh
set -eu

#  Copyright 2019 Erik Oosting
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

CURRENT=$(pwd)
NAME=$1
DISTINFO=$(curl -s https://registry.npmjs.com/$NAME/latest | jq .dist)
SRC=$(echo $DISTINFO | jq .tarball)
INTEGRITY=$(echo $DISTINFO | jq .shasum)
PROJECT=$(mktemp -d)
echo $PROJECT
mkdir -p $NAME
cd $PROJECT
curl -so $NAME.tgz ${SRC:1:-1} 
tar -xzf $NAME.tgz
node2nix --nodejs-14 -i ./package/package.json
REPLACEMENT="src = fetchurl { url = $SRC; sha1 = $INTEGRITY; }"
sed -i "s#src = ./package#$REPLACEMENT#g" node-packages.nix
rm -rf package $NAME.tgz
mv $PROJECT/* $CURRENT/$NAME
rm -d $PROJECT
